### ISSUE TITLE
testing registration, login flow, save profile for site:user

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/cats-core#17]
- [x] register through registration portal (#1) 4402daf3731b27a4971542012dfd32c060e97673

- [x] login 4e0866b4dca1f4415661f85562931945fb1eb954

- [x] validated as site:user with site:user menu (#3)

- [x] save profile data (#6)
- [x] open profile page (#7)
    currently open via edit page

**Comment by renowijoyo** [comment]
- [ ] register through registration portal

- [ ] login

- [ ] validated as site:user with site:user menu

- [ ] open profile page

- [ ] save profile data
